// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Slush.Data;

#nullable disable

namespace Slush.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240508123654_fix-relations")]
    partial class fixrelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Slush.Data.Entity.Categories", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbCategories");
                });

            modelBuilder.Entity("Slush.Data.Entity.CategoryByAuthor", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbCategoriesByAuthors");
                });

            modelBuilder.Entity("Slush.Data.Entity.CategoryByUser", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbCategoriesByUsers");
                });

            modelBuilder.Entity("Slush.Data.Entity.CategoryForGame", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("categoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("dbCategoriesForGame");
                });

            modelBuilder.Entity("Slush.Data.Entity.Community.GameGroup.GameComment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("authorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("gamePostId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("dbGameComments");
                });

            modelBuilder.Entity("Slush.Data.Entity.Community.GameGroup.GameGroup", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("dbGameGroups");
                });

            modelBuilder.Entity("Slush.Data.Entity.Community.GameGroup.GameGuide", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("authorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("discussionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("dislikesCount")
                        .HasColumnType("int");

                    b.Property<Guid>("gameGroupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<int>("likesCount")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbGameGuides");
                });

            modelBuilder.Entity("Slush.Data.Entity.Community.GameGroup.GameNews", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("authorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("discussionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("dislikesCount")
                        .HasColumnType("int");

                    b.Property<Guid>("gameGroupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<int>("likesCount")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbGameNews");
                });

            modelBuilder.Entity("Slush.Data.Entity.Community.GameGroup.GamePosts", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("authorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("discussionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("dislikesCount")
                        .HasColumnType("int");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("gameTopicId")
                        .HasColumnType("char(36)");

                    b.Property<int>("likesCount")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbGamePosts");
                });

            modelBuilder.Entity("Slush.Data.Entity.Community.GameGroup.GameTopic", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("attachedId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbGameTopics");
                });

            modelBuilder.Entity("Slush.Data.Entity.Community.Group", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("attachedId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbGroups");
                });

            modelBuilder.Entity("Slush.Data.Entity.Community.GroupComment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("groupId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("dbGroupComments");
                });

            modelBuilder.Entity("Slush.Data.Entity.Community.Post", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("authorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("discussionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("dislikesCount")
                        .HasColumnType("int");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<int>("likesCount")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbPosts");
                });

            modelBuilder.Entity("Slush.Data.Entity.Community.Topic", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("attachedId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("authorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("postId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("dbTopics");
                });

            modelBuilder.Entity("Slush.Data.Entity.Language", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbLanguages");
                });

            modelBuilder.Entity("Slush.Data.Entity.LanguageInGame", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("languageId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("dbLanguagesInGame");
                });

            modelBuilder.Entity("Slush.Data.Entity.MaximumSystemRequirement", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("freeDiskSpace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<string>("processor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("video")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbMaximumSystemRequirements");
                });

            modelBuilder.Entity("Slush.Data.Entity.MinimalSystemRequirement", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("freeDiskSpace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<string>("processor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("video")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbMinimalSystemRequirements");
                });

            modelBuilder.Entity("Slush.Data.Entity.Profile.Screenshot", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("authorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("discussionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("dislikesCount")
                        .HasColumnType("int");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<int>("likesCount")
                        .HasColumnType("int");

                    b.Property<string>("screenshotUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbScreenshots");
                });

            modelBuilder.Entity("Slush.Data.Entity.Profile.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("passwordSalt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbUsers");
                });

            modelBuilder.Entity("Slush.Data.Entity.Profile.UserComment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("authorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("dbUserComments");
                });

            modelBuilder.Entity("Slush.Data.Entity.Profile.Video", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("authorId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<Guid>("discussionId")
                        .HasColumnType("char(36)");

                    b.Property<int>("dislikesCount")
                        .HasColumnType("int");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<int>("likesCount")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("videoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbVideos");
                });

            modelBuilder.Entity("Slush.Data.Entity.SystemRequirement", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("OS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RAM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("freeDiskSpace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<string>("processor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("video")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbSystemRequirements");
                });

            modelBuilder.Entity("Slush.Entity.Profile.Friends", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("friendId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("dbFriends");
                });

            modelBuilder.Entity("Slush.Entity.Profile.OwnedGame", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ownedGameId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("dbOwnedGames");
                });

            modelBuilder.Entity("Slush.Entity.Profile.WishedGame", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ownedGameId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("userId")
                        .HasColumnType("char(36)");

                    b.HasKey("id");

                    b.ToTable("dbWishedGames");
                });

            modelBuilder.Entity("Slush.Entity.Store.Product.Creators.Developer", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("backgroundImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("subscribersCount")
                        .HasColumnType("int");

                    b.Property<string>("urlForNewsPage")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbDevelopers");
                });

            modelBuilder.Entity("Slush.Entity.Store.Product.Creators.Publisher", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("avatar")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("backgroundImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("subscribersCount")
                        .HasColumnType("int");

                    b.Property<string>("urlForNewsPage")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbPublishers");
                });

            modelBuilder.Entity("Slush.Entity.Store.Product.DLCInShop", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dateOfRelease")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("developerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("discount")
                        .HasColumnType("int");

                    b.Property<Guid>("gameId")
                        .HasColumnType("char(36)");

                    b.Property<string>("gameImages")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("previeImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("price")
                        .HasColumnType("float");

                    b.Property<Guid>("publisherId")
                        .HasColumnType("char(36)");

                    b.Property<string>("urlForContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbDLCsInShop");
                });

            modelBuilder.Entity("Slush.Entity.Store.Product.GameInShop", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("createdAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("dateOfRelease")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("deleteAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("developerId")
                        .HasColumnType("char(36)");

                    b.Property<int>("discount")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("previeImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("price")
                        .HasColumnType("float");

                    b.Property<Guid>("publisherId")
                        .HasColumnType("char(36)");

                    b.Property<string>("urlForContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("dbGamesInShops");
                });

            modelBuilder.Entity("System.Collections.Generic.List<object>", b =>
                {
                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.ToTable("List<object>");
                });
#pragma warning restore 612, 618
        }
    }
}
